version: "3.7"
services:
  rails:
    build:
      context: ./docker
    command: bundle exec rails server -u puma -p 3000 -b '0.0.0.0'
    # command: bash -i
    tty: true
    entrypoint: docker/entrypoint.sh
    volumes:
      - .:/app
      - gems:/gems
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache
volumes:
  gems:
  node_modules:
  packs:
  rails_cache:
